from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class OrganizationEnrichmentQuery(BaseModel):
    domain: str = Field()

class PrimaryPhone(BaseModel):
    languages: Optional[List[str]] = Field(default=None)
    phone: Optional[str] = Field(default=None)

class FundingEvent(BaseModel):
    id: str = Field()
    date: str = Field()
    news_url: Optional[str] = Field(default=None)
    type: str = Field()
    investors: Optional[str] = Field(default=None)
    amount: Optional[str] = Field(default=None)
    currency: Optional[str] = Field(default=None)

class Account(BaseModel):
    id: str = Field()
    domain: str = Field()
    name: str = Field()
    team_id: str = Field()
    organization_id: str = Field()
    account_stage_id: Optional[str] = Field(default=None)
    source: str = Field()
    original_source: str = Field()
    creator_id: Optional[str] = Field(default=None)
    owner_id: str = Field()
    created_at: str = Field()
    phone: str = Field()
    phone_status: str = Field()
    hubspot_id: Optional[str] = Field(default=None)
    salesforce_id: Optional[str] = Field(default=None)
    crm_owner_id: Optional[str] = Field(default=None)
    parent_account_id: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    sanitized_phone: str = Field()
    account_playbook_statuses: List[Any] = Field(default_factory=list)
    account_rule_config_statuses: Optional[List[Any]] = Field(default=None)
    existence_level: str = Field()
    label_ids: List[str] = Field()
    typed_custom_fields: Dict[str, Any] = Field()
    custom_field_errors: Dict[str, Any] = Field()
    modality: str = Field()
    source_display_name: str = Field()
    crm_record_url: Optional[str] = Field(default=None)
    intent_strength: Optional[str] = Field(default=None)
    show_intent: Optional[bool] = Field(default=None)
    has_intent_signal_account: Optional[bool] = Field(default=None)
    intent_signal_signal_account: Optional[str] = Field(default=None)

class DepartmentalHeadCount(BaseModel):
    engineering: Optional[int] = Field(default=None)
    operations: Optional[int] = Field(default=None)
    support: Optional[int] = Field(default=None)
    marketing: Optional[int] = Field(default=None)
    human_resources: Optional[int] = Field(default=None)
    sales: Optional[int] = Field(default=None)
    finance: Optional[int] = Field(default=None)
    consulting: Optional[int] = Field(default=None)
    legal: Optional[int] = Field(default=None)
    arts_and_design: Optional[int] = Field(default=None)
    accounting: Optional[int] = Field(default=None)
    business_development: Optional[int] = Field(default=None)
    information_technology: Optional[int] = Field(default=None)
    education: Optional[int] = Field(default=None)
    media_and_commmunication: Optional[int] = Field(default=None)
    product_management: Optional[int] = Field(default=None)
    entrepreneurship: Optional[int] = Field(default=None)
    data_science: Optional[int] = Field(default=None)
    administrative: Optional[int] = Field(default=None)

class CurrentTechnology(BaseModel):
    uid: str = Field()
    name: str = Field()
    category: str = Field()

class IndustryTagHash(BaseModel):
    information_technology_services: Optional[str] = Field(default=None)

class Organization(BaseModel):
    id: Optional[str] = Field(default=None)
    name: Optional[str] = Field(default=None)
    website_url: Optional[str] = Field(default=None)
    blog_url: Optional[str] = Field(default=None)
    angellist_url: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    facebook_url: Optional[str] = Field(default=None)
    primary_phone: Optional[PrimaryPhone] = Field(default=None)
    languages: Optional[List[Any]] = Field(default=None)
    alexa_ranking: Optional[int] = Field(default=0)
    phone: Optional[str] = Field(default=None)
    linkedin_uid: Optional[str] = Field(default=None)
    founded_year: Optional[int] = Field(default=0)
    publicly_traded_symbol: Optional[str] = Field(default=None)
    publicly_traded_exchange: Optional[str] = Field(default=None)
    logo_url: Optional[str] = Field(default=None)
    crunchbase_url: Optional[str] = Field(default=None)
    primary_domain: Optional[str] = Field(default=None)
    industry: Optional[str] = Field(default=None)
    keywords: List[str] = Field()
    estimated_num_employees: Optional[int] = Field(default=0)
    industries: List[str] = Field()
    secondary_industries: List[Any] = Field()
    snippets_loaded: bool = Field(default=True)
    industry_tag_id: Optional[str] = Field(default=None)
    industry_tag_hash: IndustryTagHash = Field()
    retail_location_count: Optional[int] = Field(default=0)
    raw_address: Optional[str] = Field(default=None)
    street_address: Optional[str] = Field(default=None)
    city: Optional[str] = Field(default=None)
    state: Optional[str] = Field(default=None)
    postal_code: Optional[str] = Field(default=None)
    country: Optional[str] = Field(default=None)
    owned_by_organization_id: Optional[str] = Field(default=None)
    seo_description: Optional[str] = Field(default=None)
    short_description: Optional[str] = Field(default=None)
    suborganizations: List[Any] = Field()
    num_suborganizations: Optional[int] = Field(default=0)
    annual_revenue_printed: Optional[str] = Field(default=None)
    annual_revenue: Optional[int] = Field(default=0)
    total_funding: Optional[int] = Field(default=None)
    total_funding_printed: Optional[str] = Field(default=None)
    latest_funding_round_date: Optional[str] = Field(default=None)
    latest_funding_stage: Optional[str] = Field(default=None)
    funding_events: Optional[List[FundingEvent]] = Field(default=None)
    technology_names: List[str] = Field()
    current_technologies: List[CurrentTechnology] = Field()
    org_chart_root_people_ids: List[str] = Field()
    org_chart_sector: Optional[str] = Field(default=None)
    org_chart_removed: Optional[bool] = Field(default=None)
    org_chart_show_department_filter: Optional[bool] = Field(default=None)
    account_id: Optional[str] = Field(default=None)
    account: Optional[Account] = Field(default=None)
    departmental_head_count: DepartmentalHeadCount = Field()

class OrganizationEnrichmentResponse(BaseModel):
    organization: Organization = Field()
