from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class PeopleSearchQuery(BaseModel):
    person_titles: Optional[List[str]] = Field(default=None)
    include_similar_titles: Optional[bool] = Field(default=True, description="Match similar titles (default: True)")
    person_locations: Optional[List[str]] = Field(default=None)
    person_seniorities: Optional[List[str]] = Field(default=None)
    organization_locations: Optional[List[str]] = Field(default=None)
    q_organization_domains_list: Optional[List[str]] = Field(default=None, description="Filter by company domains (e.g., ['apollo.io'])")
    contact_email_status: Optional[List[str]] = Field(default=None)
    organization_ids: Optional[List[str]] = Field(default=None)
    organization_num_employees_ranges: Optional[List[str]] = Field(default=None, description="Employee count ranges (e.g., ['1,10', '11,50'])")
    q_keywords: Optional[str] = Field(default=None, description="Search keywords across all fields")
    page: Optional[int] = Field(default=None)
    per_page: Optional[int] = Field(default=None)

class Breadcrumb(BaseModel):
    label: str = Field()
    signal_field_name: str = Field()
    value: str = Field()
    display_name: str = Field()

class DialerFlags(BaseModel):
    country_name: str = Field()
    country_enabled: bool = Field()
    high_risk_calling_enabled: bool = Field()
    potential_high_risk_number: bool = Field()

class PhoneNumber(BaseModel):
    raw_number: str = Field()
    sanitized_number: Optional[str] = Field(default=None)
    type: str = Field()
    position: int = Field()
    status: str = Field()
    dnc_status: Optional[str] = Field(default=None)
    dnc_other_info: Optional[Any] = Field(default=None)
    dialer_flags: Optional[DialerFlags] = Field(default=None)

class ContactEmail(BaseModel):
    email: str = Field()
    email_md5: str = Field()
    email_sha256: str = Field()
    email_status: str = Field()
    email_source: Optional[str] = Field(default=None)
    extrapolated_email_confidence: Optional[str] = Field(default=None)
    position: int = Field()
    email_from_customer: Optional[str] = Field(default=None)
    free_domain: bool = Field()

class Account(BaseModel):
    id: str = Field()
    name: str = Field()
    website_url: Optional[str] = Field(default=None)
    blog_url: Optional[str] = Field(default=None)
    angellist_url: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    facebook_url: Optional[str] = Field(default=None)
    primary_phone: Optional[Dict[str, Any]] = Field(default=None)
    languages: Optional[List[Any]] = Field(default=None)
    alexa_ranking: Optional[int] = Field(default=None)
    phone: Optional[str] = Field(default=None)
    linkedin_uid: Optional[str] = Field(default=None)
    founded_year: Optional[int] = Field(default=None)
    publicly_traded_symbol: Optional[str] = Field(default=None)
    publicly_traded_exchange: Optional[str] = Field(default=None)
    logo_url: Optional[str] = Field(default=None)
    crunchbase_url: Optional[str] = Field(default=None)
    primary_domain: Optional[str] = Field(default=None)
    domain: Optional[str] = Field(default=None)
    team_id: Optional[str] = Field(default=None)
    organization_id: Optional[str] = Field(default=None)
    account_stage_id: Optional[str] = Field(default=None)
    source: Optional[str] = Field(default=None)
    original_source: Optional[str] = Field(default=None)
    creator_id: Optional[str] = Field(default=None)
    owner_id: Optional[str] = Field(default=None)
    created_at: Optional[str] = Field(default=None)
    phone_status: Optional[str] = Field(default=None)
    hubspot_id: Optional[str] = Field(default=None)
    salesforce_id: Optional[str] = Field(default=None)
    crm_owner_id: Optional[str] = Field(default=None)
    parent_account_id: Optional[str] = Field(default=None)
    sanitized_phone: Optional[str] = Field(default=None)
    account_playbook_statuses: Optional[List[Any]] = Field(default=None)
    account_rule_config_statuses: Optional[List[Any]] = Field(default=None)
    existence_level: Optional[str] = Field(default=None)
    label_ids: Optional[List[str]] = Field(default=None)
    typed_custom_fields: Optional[Dict[str, Any]] = Field(default=None)
    custom_field_errors: Optional[Dict[str, Any]] = Field(default=None)
    modality: Optional[str] = Field(default=None)
    source_display_name: Optional[str] = Field(default=None)
    salesforce_record_url: Optional[str] = Field(default=None)
    crm_record_url: Optional[str] = Field(default=None)

class EmploymentHistory(BaseModel):
    id: str = Field()
    created_at: Optional[str] = Field(default=None)
    current: Optional[bool] = Field(default=None)
    degree: Optional[str] = Field(default=None)
    description: Optional[str] = Field(default=None)
    emails: Optional[str] = Field(default=None)
    end_date: Optional[str] = Field(default=None)
    grade_level: Optional[str] = Field(default=None)
    kind: Optional[str] = Field(default=None)
    major: Optional[str] = Field(default=None)
    organization_id: Optional[str] = Field(default=None)
    organization_name: Optional[str] = Field(default=None)
    raw_address: Optional[str] = Field(default=None)
    start_date: Optional[str] = Field(default=None)
    title: Optional[str] = Field(default=None)
    updated_at: Optional[str] = Field(default=None)
    key: Optional[str] = Field(default=None)

class Organization(BaseModel):
    id: str = Field()
    name: str = Field()
    website_url: Optional[str] = Field(default=None)
    blog_url: Optional[str] = Field(default=None)
    angellist_url: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    facebook_url: Optional[str] = Field(default=None)
    primary_phone: Optional[Dict[str, Any]] = Field(default=None)
    languages: Optional[List[Any]] = Field(default=None)
    alexa_ranking: Optional[int] = Field(default=None)
    phone: Optional[str] = Field(default=None)
    linkedin_uid: Optional[str] = Field(default=None)
    founded_year: Optional[int] = Field(default=None)
    publicly_traded_symbol: Optional[str] = Field(default=None)
    publicly_traded_exchange: Optional[str] = Field(default=None)
    logo_url: Optional[str] = Field(default=None)
    crunchbase_url: Optional[str] = Field(default=None)
    primary_domain: Optional[str] = Field(default=None)

class Contact(BaseModel):
    contact_roles: List[Any] = Field()
    id: str = Field()
    first_name: str = Field()
    last_name: str = Field()
    name: str = Field()
    linkedin_url: str = Field()
    title: str = Field()
    contact_stage_id: str = Field()
    owner_id: str = Field()
    creator_id: str = Field()
    person_id: str = Field()
    email_needs_tickling: bool = Field()
    organization_name: str = Field()
    source: str = Field()
    original_source: str = Field()
    organization_id: str = Field()
    headline: str = Field()
    photo_url: Optional[str] = Field(default=None)
    present_raw_address: Optional[str] = Field(default=None)
    linkedin_uid: Optional[str] = Field(default=None)
    extrapolated_email_confidence: Optional[str] = Field(default=None)
    salesforce_id: Optional[str] = Field(default=None)
    salesforce_lead_id: Optional[str] = Field(default=None)
    salesforce_contact_id: Optional[str] = Field(default=None)
    salesforce_account_id: Optional[str] = Field(default=None)
    crm_owner_id: Optional[str] = Field(default=None)
    created_at: str = Field()
    emailer_campaign_ids: List[str] = Field()
    direct_dial_status: Optional[str] = Field(default=None)
    direct_dial_enrichment_failed_at: Optional[str] = Field(default=None)
    email_status: Optional[str] = Field(default=None)
    email_source: Optional[str] = Field(default=None)
    account_id: Optional[str] = Field(default=None)
    last_activity_date: Optional[str] = Field(default=None)
    hubspot_vid: Optional[str] = Field(default=None)
    hubspot_company_id: Optional[str] = Field(default=None)
    crm_id: Optional[str] = Field(default=None)
    sanitized_phone: Optional[str] = Field(default=None)
    merged_crm_ids: Optional[str] = Field(default=None)
    updated_at: Optional[str] = Field(default=None)
    queued_for_crm_push: Optional[bool] = Field(default=None)
    suggested_from_rule_engine_config_id: Optional[str] = Field(default=None)
    email_unsubscribed: Optional[str] = Field(default=None)
    label_ids: List[Any] = Field()
    has_pending_email_arcgate_request: bool = Field()
    has_email_arcgate_request: bool = Field()
    existence_level: str = Field()
    email: str = Field()
    email_from_customer: Optional[str] = Field(default=None)
    typed_custom_fields: Dict[str, Any] = Field(default_factory=dict)
    custom_field_errors: Dict[str, Any] = Field(default_factory=dict)
    salesforce_record_url: Optional[str] = Field(default=None)
    crm_record_url: Optional[str] = Field(default=None)
    email_status_unavailable_reason: Optional[str] = Field(default=None)
    email_true_status: Optional[str] = Field(default=None)
    updated_email_true_status: bool = Field()
    contact_rule_config_statuses: Optional[List[Dict[str, Any]]] = Field(default=None)
    source_display_name: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    contact_campaign_statuses: List[Dict[str, Any]] = Field()
    state: str = Field()
    city: str = Field()
    country: str = Field()
    account: Account = Field()
    contact_emails: List[ContactEmail] = Field()
    organization: Organization = Field()
    employment_history: List[EmploymentHistory] = Field()
    time_zone: str = Field()
    intent_strength: Optional[str] = Field(default=None)
    show_intent: bool = Field()
    phone_numbers: List[PhoneNumber] = Field(default_factory=list)
    account_phone_note: Optional[str] = Field(default=None)
    free_domain: bool = Field()
    is_likely_to_engage: Optional[bool] = Field(default=None)
    email_domain_catchall: bool = Field()
    contact_job_change_event: Optional[str] = Field(default=None)

class Pagination(BaseModel):
    page: int = Field()
    per_page: int = Field()
    total_entries: int = Field()
    total_pages: int = Field()

class PeopleSearchResponse(BaseModel):
    # breadcrumbs: Optional[List[Breadcrumb]] = Field(default=None)
    partial_results_only: Optional[bool] = Field(default=None)
    has_join: Optional[bool] = Field(default=None)
    disable_eu_prospecting: Optional[bool] = Field(default=None)
    partial_results_limit: Optional[int] = Field(default=None)
    pagination: Optional[Pagination] = Field(default=None)
    contacts: Optional[List[Contact]] = Field(default=None)
    people: Optional[List[Any]] = Field(default=None)
    model_ids: Optional[List[str]] = Field(default=None)
    num_fetch_result: Optional[str] = Field(default=None)
    # derived_params: Optional[str] = Field(default=None)
