from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field

class PeopleEnrichmentQuery(BaseModel):
    first_name: Optional[str] = Field(default=None)
    last_name: Optional[str] = Field(default=None)
    name: Optional[str] = Field(default=None)
    email: Optional[str] = Field(default=None)
    hashed_email: Optional[str] = Field(default=None, description="SHA-256 hashed email for privacy")
    organization_name: Optional[str] = Field(default=None)
    domain: Optional[str] = Field(default=None)
    id: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    reveal_personal_emails: Optional[bool] = Field(default=False, description="Reveals personal emails (consumes credits)")
    reveal_phone_number: Optional[bool] = Field(default=False, description="Reveals phone (consumes credits, requires webhook_url)")
    webhook_url: Optional[str] = Field(default=None, description="Required when reveal_phone_number=True")

class EmploymentHistory(BaseModel):
    id: str = Field()
    created_at: Optional[str] = Field(default=None)
    current: bool = Field(default=True)
    degree: Optional[str] = Field(default=None)
    description: Optional[str] = Field(default=None)
    emails: Optional[str] = Field(default=None)
    end_date: Optional[str] = Field(default=None)
    grade_level: Optional[str] = Field(default=None)
    kind: Optional[str] = Field(default=None)
    major: Optional[str] = Field(default=None)
    organization_id: Optional[str] = Field(default=None)
    organization_name: str = Field()
    raw_address: Optional[str] = Field(default=None)
    start_date: str = Field()
    title: str = Field()
    updated_at: Optional[str] = Field(default=None)
    id: str = Field()
    key: str = Field()
    state: Optional[str] = Field(default=None)
    city: Optional[str] = Field(default=None)
    country: Optional[str] = Field(default=None)
    contact_id: Optional[str] = Field(default=None)

class Contact(BaseModel):
    contact_roles: List[Any] = Field()
    id: str = Field()
    first_name: str = Field()
    last_name: str = Field()
    name: str = Field()
    linkedin_url: str = Field()
    title: str = Field()
    contact_stage_id: str = Field()
    owner_id: Optional[str] = Field(default=None)
    creator_id: str = Field()
    person_id: str = Field()
    email_needs_tickling: Optional[bool] = Field(default=None)
    organization_name: str = Field()
    source: str = Field()
    original_source: str = Field()
    organization_id: str = Field()
    headline: str = Field()
    photo_url: Optional[str] = Field(default=None)
    present_raw_address: str = Field()
    linkedin_uid: Optional[str] = Field(default=None)
    extrapolated_email_confidence: Optional[str] = Field(default=None)
    salesforce_id: Optional[str] = Field(default=None)
    salesforce_lead_id: Optional[str] = Field(default=None)
    salesforce_contact_id: Optional[str] = Field(default=None)
    salesforce_account_id: Optional[str] = Field(default=None)
    crm_owner_id: Optional[str] = Field(default=None)
    created_at: str = Field()
    emailer_campaign_ids: List[Any] = Field()
    direct_dial_status: Optional[str] = Field(default=None)
    direct_dial_enrichment_failed_at: Optional[str] = Field(default=None)
    email_status: str = Field()
    email_source: Optional[str] = Field(default=None)
    account_id: str = Field()
    last_activity_date: Optional[str] = Field(default=None)
    hubspot_vid: Optional[str] = Field(default=None)
    hubspot_company_id: Optional[str] = Field(default=None)
    crm_id: Optional[str] = Field(default=None)
    sanitized_phone: str = Field()
    merged_crm_ids: Optional[str] = Field(default=None)
    updated_at: str = Field()
    queued_for_crm_push: Optional[str] = Field(default=None)
    suggested_from_rule_engine_config_id: Optional[str] = Field(default=None)
    email_unsubscribed: Optional[bool] = Field(default=None)
    label_ids: List[Any] = Field()
    has_pending_email_arcgate_request: bool = Field()
    has_email_arcgate_request: bool = Field()
    existence_level: str = Field()
    email: str = Field()
    email_from_customer: bool = Field()
    typed_custom_fields: Dict[str, Any] = Field()
    custom_field_errors: Optional[str] = Field(default=None)
    crm_record_url: Optional[str] = Field(default=None)
    email_status_unavailable_reason: Optional[str] = Field(default=None)
    email_true_status: str = Field()
    updated_email_true_status: bool = Field()
    contact_rule_config_statuses: List[Any] = Field()
    source_display_name: str = Field()
    contact_emails: List[Dict[str, Any]] = Field()
    time_zone: str = Field()
    phone_numbers: List[Dict[str, Any]] = Field()
    account_phone_note: Optional[str] = Field(default=None)
    free_domain: bool = Field()
    is_likely_to_engage: bool = Field()

class Organization(BaseModel):
    id: str = Field()
    name: str = Field()
    website_url: Optional[str] = Field(default=None)
    blog_url: Optional[str] = Field(default=None)
    angellist_url: Optional[str] = Field(default=None)
    linkedin_url: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    facebook_url: Optional[str] = Field(default=None)
    primary_phone: Optional[Dict[str, Any]] = Field(default=None)
    languages: Optional[List[Any]] = Field(default=None)
    alexa_ranking: Optional[int] = Field(default=None)
    phone: Optional[str] = Field(default=None)
    linkedin_uid: Optional[str] = Field(default=None)
    founded_year: Optional[int] = Field(default=None)
    publicly_traded_symbol: Optional[str] = Field(default=None)
    publicly_traded_exchange: Optional[str] = Field(default=None)
    logo_url: Optional[str] = Field(default=None)
    crunchbase_url: Optional[str] = Field(default=None)
    primary_domain: Optional[str] = Field(default=None)
    industry: Optional[str] = Field(default=None)
    keywords: Optional[List[str]] = Field(default=None)
    estimated_num_employees: Optional[int] = Field(default=None)
    industries: Optional[List[str]] = Field(default=None)
    secondary_industries: Optional[List[Any]] = Field(default=None)
    snippets_loaded: Optional[bool] = Field(default=None)
    industry_tag_id: Optional[str] = Field(default=None)
    industry_tag_hash: Optional[Dict[str, str]] = Field(default=None)
    retail_location_count: Optional[int] = Field(default=None)
    raw_address: Optional[str] = Field(default=None)
    street_address: Optional[str] = Field(default=None)
    city: Optional[str] = Field(default=None)
    state: Optional[str] = Field(default=None)
    postal_code: Optional[str] = Field(default=None)
    country: Optional[str] = Field(default=None)
    owned_by_organization_id: Optional[str] = Field(default=None)
    seo_description: Optional[str] = Field(default=None)
    short_description: Optional[str] = Field(default=None)
    suborganizations: Optional[List[Any]] = Field(default=None)
    num_suborganizations: Optional[int] = Field(default=None)
    annual_revenue_printed: Optional[str] = Field(default=None)
    annual_revenue: Optional[int] = Field(default=None)
    total_funding: Optional[int] = Field(default=None)
    total_funding_printed: Optional[str] = Field(default=None)
    latest_funding_round_date: Optional[str] = Field(default=None)
    latest_funding_stage: Optional[str] = Field(default=None)
    funding_events: Optional[List[Dict[str, Any]]] = Field(default=None)
    technology_names: Optional[List[str]] = Field(default=None)
    current_technologies: Optional[List[Dict[str, Any]]] = Field(default=None)
    org_chart_root_people_ids: Optional[List[str]] = Field(default=None)
    org_chart_sector: Optional[str] = Field(default=None)
    org_chart_removed: Optional[bool] = Field(default=None)
    org_chart_show_department_filter: Optional[bool] = Field(default=None)

class PeopleEnrichmentResponse(BaseModel):
    person: Optional["Person"] = None

class Person(BaseModel):
    id: str = Field()
    first_name: str = Field()
    last_name: str = Field()
    name: str = Field()
    linkedin_url: Optional[str] = Field(default=None)
    title: Optional[str] = Field(default=None)
    email_status: Optional[str] = Field(default=None)
    photo_url: Optional[str] = Field(default=None)
    twitter_url: Optional[str] = Field(default=None)
    github_url: Optional[str] = Field(default=None)
    facebook_url: Optional[str] = Field(default=None)
    extrapolated_email_confidence: Optional[str] = Field(default=None)
    headline: Optional[str] = Field()
    email: Optional[str] = Field()
    organization_id: Optional[str] = Field()
    employment_history: List[EmploymentHistory] = Field()
    state: Optional[str] = Field(default=None)
    city: Optional[str] = Field(default=None)
    country: Optional[str] = Field(default=None)
    contact_id: Optional[str] = Field(default=None)
    contact: Optional[Contact] = Field(default=None)
    revealed_for_current_team: bool = Field()
    organization: Optional[Organization] = Field(default=None)
    is_likely_to_engage: Optional[bool] = Field(default=None)
    intent_strength: Optional[str] = Field(default=None)
    show_intent: bool = Field()
    departments: List[str] = Field()
    subdepartments: List[str] = Field()
    functions: List[str] = Field()
    seniority: Optional[str] = Field()
