[project]
name = "apollo-io-mcp-server"
version = "0.1.0"
description = "MCP server that exposes the Apollo.io API functionalities as tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
]
